<?php

/**
 * This is the model base class for the table "users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "users" available as properties of the model,
 * followed by relations of table "users" available as properties of the model.
 *
 * @property integer $id
 * @property string $firstname
 * @property string $middlename
 * @property string $lastname
 * @property string $username
 * @property string $password
 * @property string $salt
 * @property integer $groupe
 * @property integer $status
 *
 * @property Hospital[] $hospitals
 */
abstract class BaseUsers extends GxActiveRecord {

	public $old_password;
    public $new_password;
    public $repeat_password;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Users|Users', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('firstname, lastname, username, password, salt, groupe, status', 'required'),
			array('groupe, status', 'numerical', 'integerOnly'=>true),
			array('firstname, middlename, lastname, username', 'length', 'max'=>20),
			array('password, salt', 'length', 'max'=>32),
			array('id, firstname, middlename, lastname, username, password, salt, groupe, status', 'safe', 'on'=>'search'),

	        array('old_password, new_password, repeat_password', 'required', 'on' => 'changePwd'),
	        array('old_password', 'findPasswords', 'on' => 'changePwd'),
	        array('repeat_password', 'compare', 'compareAttribute'=>'new_password', 'on'=>'changePwd'),
     
		);
	}

	public function relations() {
		return array(
			'hospitals' => array(self::HAS_MANY, 'Hospital', 'iduser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firstname' => Yii::t('app', 'Firstname'),
			'middlename' => Yii::t('app', 'Middlename'),
			'lastname' => Yii::t('app', 'Lastname'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'salt' => Yii::t('app', 'Salt'),
			'groupe' => Yii::t('app', 'Groupe'),
			'status' => Yii::t('app', 'Status'),
			'hospitals' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
        if(isset($_GET['p'])){

        	 $criteria->addCondition('id='.Yii::app()->user->id);
        }

		$criteria->compare('id', $this->id);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('middlename', $this->middlename, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('salt', $this->salt, true);
		$criteria->compare('groupe', $this->groupe);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}


	/************************************* Login *********************************************************/
	// hash password
public function hashPassword($password, $salt)
{
    return md5($salt.$password);
}
        
// password validation
public function validatePassword($password)
{
    return $this->hashPassword($password,$this->salt)===$this->password;
}
        
//generate salt
public function generateSalt()
{
    return uniqid('',true);
}
        
public function beforeValidate()
{
    $this->salt = $this->generateSalt();
    return parent::beforeValidate();
}
        
public function beforeSave()
{
    $this->password = $this->hashPassword($this->password, $this->salt);
    return parent::beforeSave();
}

static function getGroupes()
{
return array(
    array('id'=>'1', 'groupe'=>'Clerk Desk of Hospital'),
    array('id'=>'2', 'groupe'=>'Clerk Desk of Pharmacy'),
    array('id'=>'3', 'groupe'=>'MIS Accountant'),
    array('id'=>'4', 'groupe'=>'MIS Admin'),
    array('id'=>'5', 'groupe'=>'MIS Manager'),
    array('id'=>'6', 'groupe'=>'MIS Pharmacist'),
);
}

static function getGroupe($onoff)
{
if($onoff == 1) 
    return 'Clerk Desk of Hospital';
else if($onoff == 2) 
    return 'Clerk Desk of Pharmacy';
else if($onoff == 3) 
    return 'MIS Accountant';
else if($onoff == 4) 
    return 'MIS Admin';
else if($onoff == 5) 
    return 'MIS Manager';
else 
    return 'MIS Pharmacist';
}

      public function findPasswords($attribute, $params)
    {
        $user = Users::model()->findByPk(Yii::app()->user->id);
        if ($user->password != md5($user->salt.$this->old_password))
            $this->addError($attribute, 'Old password is incorrect.');
    }

 public function Passwords()
    {
        $user = Users::model()->findByPk(Yii::app()->user->id);
        $newpassword=md5($user->salt.$this->new_password);
        return "coco";
    }
}