<?php

/**
 * This is the model base class for the table "district".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "District".
 *
 * Columns in table "district" available as properties of the model,
 * followed by relations of table "district" available as properties of the model.
 *
 * @property integer $id
 * @property string $district
 * @property integer $idprovince
 *
 * @property Province $idprovince0
 * @property Sector[] $sectors
 */
abstract class BaseDistrict extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'district';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'College|Colleges', $n);
	}

	public static function representingColumn() {
		return 'district';
	}

	public function rules() {
		return array(
			array('district, idprovince', 'required'),
			array('idprovince', 'numerical', 'integerOnly'=>true),
			array('district', 'length', 'max'=>20),
			array('id, district, idprovince', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idprovince0' => array(self::BELONGS_TO, 'Province', 'idprovince'),
			'sectors' => array(self::HAS_MANY, 'Sector', 'iddistrict'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'district' => Yii::t('app', 'College'),
			'idprovince' => null,
			'idprovince0' => null,
			'sectors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('district', $this->district, true);
		$criteria->compare('idprovince', $this->idprovince);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}