<?php

/**
 * This is the model base class for the table "price_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PriceHistory".
 *
 * Columns in table "price_history" available as properties of the model,
 * followed by relations of table "price_history" available as properties of the model.
 *
 * @property integer $id
 * @property integer $iddrug
 * @property double $ancient_price
 * @property double $new_price
 * @property string $old_changedate
 * @property string $changedate
 * @property integer $userid
 *
 * @property Users $user
 * @property Drugs $iddrug0
 */
abstract class BasePriceHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'price_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PriceHistory|PriceHistories', $n);
	}

	public static function representingColumn() {
		return 'old_changedate';
	}

	public function rules() {
		return array(
			array('iddrug, ancient_price, new_price, old_changedate, userid', 'required'),
			array('iddrug, userid', 'numerical', 'integerOnly'=>true),
			array('ancient_price, new_price', 'numerical'),
			array('old_changedate', 'length', 'max'=>50),
			array('changedate', 'safe'),
			array('changedate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, iddrug, ancient_price, new_price, old_changedate, changedate, userid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'userid'),
			'iddrug0' => array(self::BELONGS_TO, 'Drugs', 'iddrug'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'iddrug' => null,
			'ancient_price' => Yii::t('app', 'Ancient Price'),
			'new_price' => Yii::t('app', 'New Price'),
			'old_changedate' => Yii::t('app', 'Old Change Date'),
			'changedate' => Yii::t('app', 'Change Date'),
			'userid' => null,
			'user' => null,
			'iddrug0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('iddrug', $this->iddrug);
		$criteria->compare('ancient_price', $this->ancient_price);
		$criteria->compare('new_price', $this->new_price);
		$criteria->compare('old_changedate', $this->old_changedate, true);
		$criteria->compare('changedate', $this->changedate, true);
		$criteria->compare('userid', $this->userid);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}